# Configuration for results-log-server
listeners.tcp.default = 5673
management.tcp.port = 15673
stream.listeners.tcp.1 = 5553
stomp.listeners.tcp = none
mqtt.listeners.tcp = none

# Other configurations
disk_free_limit.absolute = 1GB
load_definitions = /home/alana/github/rt-constellation/rabbitmq-infrastructure/results-log-server/rabbitmq-conf/definitions.json
